# -*- coding: utf-8 -*-
"""BDR-TFg2 Extração.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oUK-9F9865o25DUvNshJVsfSid9Fx0Hg

# Ambiente

1. download
2. limpeza
3. tratamento
4. modelagem
5. criação SQLite
6. inserção tabelas
"""

import os
import time
import zipfile
import sqlite3
import requests
import pandas as pd
import re
import unicodedata
from google.colab import drive

if not os.path.exists('/content/drive/MyDrive'):
    drive.mount('/content/drive')
    print("Google Drive montado!")
else:
    print("Google Drive já montado.")

# trabalhando com intervalo de tempo em anos
ANO_INICIO = 2023
ANO_FIM    = 2026
ANOS       = list(range(ANO_INICIO, ANO_FIM + 1))

BASE_PATH = "/content/drive/MyDrive/BDR-TFg2/dados"
RAW_PATH  = f"{BASE_PATH}/raw"
PROC_PATH = f"{BASE_PATH}/processed"
DB_PATH   = f"{BASE_PATH}/database/camara.db"

for path in [RAW_PATH, PROC_PATH, os.path.dirname(DB_PATH)]:
    os.makedirs(path, exist_ok=True)

print(f"[OK] Estrutura de diretórios criada. Anos: {ANOS}")

FONTES = {
    "despesas": {
        "url":          "https://www.camara.leg.br/cotas/Ano-{ano}.csv.zip",
        "arquivo":      "Ano-{ano}.csv",
        "encoding":     "latin1",
        "fix_latin1":   True,          ###
        "numeric_cols": ["vlrliquido", "vlrdocumento"],
        "date_cols":    ["datemissao"],
        "dropna_col":   "idecadastro",
        "tabela_sql":   "Despesas",
    },
    "votacoes": {
        "url":        "https://dadosabertos.camara.leg.br/arquivos/votacoes/csv/votacoes-{ano}.csv",
        "date_cols":  ["data"],
        "tabela_sql": "Votacoes",
    },
    "proposicoes": {
        "url":        "https://dadosabertos.camara.leg.br/arquivos/proposicoes/csv/proposicoes-{ano}.csv",
        "date_cols":  ["dataapresentacao"],
        "dropna_col": "id",
        "tabela_sql": "Proposicoes",
    },
    "proposicoesAutores": {
        "url":        "https://dadosabertos.camara.leg.br/arquivos/proposicoesAutores/csv/proposicoesAutores-{ano}.csv",
        "dropna_col": "idproposicao",
        "tabela_sql": "ProposicoesAutores",
    },
    "proposicoesTemas": {
        "url":        "https://dadosabertos.camara.leg.br/arquivos/proposicoesTemas/csv/proposicoesTemas-{ano}.csv",
        "tabela_sql": "ProposicoesTemas",
    },
    "votacoesVotos": {
        "url":        "https://dadosabertos.camara.leg.br/arquivos/votacoesVotos/csv/votacoesVotos-{ano}.csv",
        "date_cols":  ["datahoraregistro"],
        "tabela_sql": "VotacoesVotos",
    },
    "votacoesOrientacoes": {
        "url":        "https://dadosabertos.camara.leg.br/arquivos/votacoesOrientacoes/csv/votacoesOrientacoes-{ano}.csv",
        "tabela_sql": "VotacoesOrientacoes",
    },
    "votacoesProposicoes": {
        "url":        "https://dadosabertos.camara.leg.br/arquivos/votacoesProposicoes/csv/votacoesProposicoes-{ano}.csv",
        "tabela_sql": "VotacoesProposicoes",
    },
    "eventos": {
        "url":        "https://dadosabertos.camara.leg.br/arquivos/eventos/csv/eventos-{ano}.csv",
        "date_cols":  ["datahorainicio"],
        "tabela_sql": "Eventos",
    },
    "eventosPresencaDeputados": {
        "url":        "https://dadosabertos.camara.leg.br/arquivos/eventosPresencaDeputados/csv/eventosPresencaDeputados-{ano}.csv",
        "tabela_sql": "EventosPresencaDeputados",
    },
    # !!! Frentessem variação de ano na URL
    "frentesDeputados": {
        "url":        "https://dadosabertos.camara.leg.br/arquivos/frentesDeputados/csv/frentesDeputados.csv",
        "tabela_sql": "FrentesDeputados",
        "anual":      False,
    },
}

"""## Funções auxiliares"""

def baixar_arquivo(url: str, destino: str) -> bool:
    """Faz download de uma URL e salva no destino."""
    print(f"    Baixando: {url}")
    try:
        response = requests.get(url, timeout=120)
        response.raise_for_status()
        with open(destino, 'wb') as f:
            f.write(response.content)
        print(f"    [OK] {destino}")
        return True
    except requests.RequestException as e:
        print(f"    [ERRO] {e}")
        return False


def extrair_zip(zip_path: str, destino: str):
    """Extrai um ZIP e remove o arquivo compactado."""
    with zipfile.ZipFile(zip_path, 'r') as zf:
        zf.extractall(destino)
    os.remove(zip_path)
    print(f"    [OK] ZIP extraído.")


def coletar_api_paginada(url_base: str, params: dict = None) -> list:
    """Coleta todos os registros de um endpoint paginado da API da Câmara."""
    params = params or {}
    params.setdefault("itens", 100)
    params["pagina"] = 1
    registros = []
    while True:
        resp = requests.get(url_base, params=params, timeout=30)
        resp.raise_for_status()
        dados = resp.json().get("dados", [])
        if not dados:
            break
        registros.extend(dados)
        params["pagina"] += 1
    return registros


def normalizar_colunas(df: pd.DataFrame) -> pd.DataFrame:
    """Padroniza nomes de colunas: strip + lowercase."""
    df.columns = df.columns.str.strip().str.lower()
    return df


def corrigir_encoding_latin1(df: pd.DataFrame) -> pd.DataFrame:
    """
    Recodifica colunas de texto que vieram corrompidas do latin1.
    Aplica encode('latin1').decode('utf-8') em todas as colunas object.
    """
    for col in df.select_dtypes(include="object").columns:
        try:
            df[col] = df[col].apply(
                lambda v: v.encode("latin1").decode("utf-8")
                if isinstance(v, str) else v
            )
        except (UnicodeEncodeError, UnicodeDecodeError):
            pass  # coluna já está em UTF-8 ou tem mix; mantém como está
    return df


def tratar_dataframe(df: pd.DataFrame, config: dict) -> pd.DataFrame:
    """Aplica todos os tratamentos declarados no catálogo."""
    df = normalizar_colunas(df)

    if config.get("fix_latin1"):
        df = corrigir_encoding_latin1(df)

    for col in config.get("numeric_cols", []):
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors='coerce')

    for col in config.get("date_cols", []):
        if col in df.columns:
            df[col] = pd.to_datetime(df[col], errors='coerce')

    dropna_col = config.get("dropna_col")
    if dropna_col and dropna_col in df.columns:
        df = df.dropna(subset=[dropna_col])

    return df


def ler_csv(caminho: str, config: dict) -> pd.DataFrame:
    """Lê um CSV com as opções do catálogo."""
    return pd.read_csv(
        caminho,
        sep=config.get("sep", ";"),
        encoding=config.get("encoding", "utf-8"),
        low_memory=False,
    )


def url_para_arquivo(url: str, nome: str, ano: int) -> str:
    """Deriva o nome de arquivo local a partir da URL."""
    if url.endswith(".zip"):
        return f"{nome}-{ano}.zip"
    return os.path.basename(url)

"""# Download, Coletas e Leituras"""

print("\n ETAPA1: DOWNLOAD ")

for nome, cfg in FONTES.items():
    eh_anual = cfg.get("anual", True)
    anos_iter = ANOS if eh_anual else [None]

    print(f"\n[FONTE] {nome}")

    for ano in anos_iter:
        url     = cfg["url"].format(ano=ano) if ano else cfg["url"]
        is_zip  = url.endswith(".zip")
        arquivo_template = cfg.get("arquivo", "{nome}-{ano}.csv")

        if ano:
            arquivo_local = arquivo_template.format(nome=nome, ano=ano)
        else:
            arquivo_local = os.path.basename(url)

        destino_zip = os.path.join(RAW_PATH, f"{nome}-{ano}.zip") if is_zip else None
        destino     = os.path.join(RAW_PATH, arquivo_local)

        if os.path.exists(destino):
            print(f"    [SKIP] {destino} já existe.")
            continue

        sucesso = baixar_arquivo(url, destino_zip or destino)

        if sucesso and is_zip:
            extrair_zip(destino_zip, RAW_PATH)

print("\n[OK] Downloads concluídos.")

print("\n=== ETAPA 2: DEPUTADOS (API) ===")

base_deputados = coletar_api_paginada("https://dadosabertos.camara.leg.br/api/v2/deputados")
print(f"  Total encontrado: {len(base_deputados)} deputados")

deputados_detalhados = []

for dep in base_deputados:
    dep_id = dep["id"]
    try:
        resp = requests.get(
            f"https://dadosabertos.camara.leg.br/api/v2/deputados/{dep_id}",
            timeout=30
        )
        resp.raise_for_status()
        d      = resp.json()["dados"]
        status = d.get("ultimoStatus", {})

        deputados_detalhados.append({
            "deputado_id":               d.get("id"),
            "nomecivil":                 d.get("nomeCivil"),
            "ultimostatus_nome":         status.get("nome"),
            "ultimostatus_nomeeleitoral": status.get("nomeEleitoral"),
            "siglapartido":              status.get("siglaPartido"),
            "siglaUF":                   status.get("siglaUf"),
            "sexo":                      d.get("sexo"),
            "escolaridade":              d.get("escolaridade"),
            "datanascimento":            d.get("dataNascimento"),
            "cpf":                       d.get("cpf"),
            "situacao":                  status.get("situacao"),
            "condicaoeleitoral":         status.get("condicaoEleitoral"),
            "urlfoto":                   status.get("urlFoto"),
        })
        time.sleep(0.1)

    except Exception as e:
        print(f"  [ERRO] Deputado {dep_id}: {e}")

df_deputados = pd.DataFrame(deputados_detalhados)
df_deputados = tratar_dataframe(df_deputados, {"date_cols": ["datanascimento"]})
print(f"  [OK] {len(df_deputados)} deputados coletados.")

print("\n=== ETAPA 3: LEITURA E TRATAMENTO ===")

dataframes = {"deputados": df_deputados}

for nome, cfg in FONTES.items():
    eh_anual = cfg.get("anual", True)
    anos_iter = ANOS if eh_anual else [None]
    partes = []

    try:
        for ano in anos_iter:
            arquivo_template = cfg.get("arquivo", "{nome}-{ano}.csv")

            if ano:
                arquivo_local = arquivo_template.format(nome=nome, ano=ano)
            else:
                arquivo_local = os.path.basename(cfg["url"])

            caminho = os.path.join(RAW_PATH, arquivo_local)

            if not os.path.exists(caminho):
                print(f"  [SKIP] {caminho} não encontrado.")
                continue

            df_ano = ler_csv(caminho, cfg)

            # Adiciona coluna de ano para rastreabilidade (apenas fontes anuais)
            if ano:
                df_ano["ano_referencia"] = ano

            partes.append(df_ano)

        if not partes:
            print(f"  [AVISO] {nome}: nenhum arquivo carregado.")
            continue

        df = pd.concat(partes, ignore_index=True)
        df = tratar_dataframe(df, cfg)
        dataframes[nome] = df
        print(f"  [OK] {nome}: {len(df):,} linhas ({len(partes)} ano(s))")

    except Exception as e:
        print(f"  [ERRO] {nome}: {e}")

votacoesVotos = dataframes["votacoesVotos"].copy()
votacoesOrientacoes = dataframes["votacoesOrientacoes"].copy()
deputados = dataframes["deputados"].copy()

deputados["escolaridade"] = (
    deputados["escolaridade"]
    .fillna("Não informado")
)

dataframes["deputados"] = deputados.copy()

PADROES_BLOCO = {
    "UNIPPFDRPSDBCID": ["UNIÃO", "PP", "PSDB", "CIDADANIA"],
    "MDBPSDREPPODE": ["MDB", "PSD", "REPUBLICANOS", "PODE"],
    "AVANSOLIDPRD": ["AVANTE", "SOLIDARIEDADE", "PRD"],
    "UNIPPPSD": ["UNIÃO", "PP", "PSD"],
    "PLFDRPTUNIPP": ["PL", "PT", "UNIÃO", "PP"],
    "PLUNIPPPSD": ["PL", "UNIÃO", "PP", "PSD"],
    "MDBPSDREPPODEPSC": ["MDB", "PSD", "REPUBLICANOS", "PODE", "PSC"]
}

def extrair_siglas(sigla):

    if pd.isna(sigla):
        return []

    texto = str(sigla).strip()
    texto_upper = texto.upper()

    # Federações
    if texto_upper.startswith("FDR"):

        texto = re.sub(
            r"^FDR\s*",
            "",
            texto,
            flags=re.IGNORECASE
        )

        return [
            x.strip()
            for x in texto.split("-")
        ]

    # Blocos
    if texto_upper.startswith("BL"):

        chave = re.sub(
            r'[^A-Z]',
            '',
            texto_upper.replace("BL", "")
        )

        for padrao, partidos in PADROES_BLOCO.items():

            if chave.startswith(padrao):
                return partidos

    return []

novos_registros = []

for _, row in votacoesOrientacoes.iterrows():

    # mantém registro original
    novos_registros.append(row.to_dict())

    siglas = extrair_siglas(row["siglabancada"])

    for sigla in siglas:

        nova_linha = row.to_dict()
        nova_linha["siglabancada"] = sigla

        novos_registros.append(nova_linha)

votacoesOrientacoes = pd.DataFrame(novos_registros)

def normalizar_partido(texto):

    if pd.isna(texto):
        return None

    texto = str(texto).strip().upper()

    texto = ''.join(
        c for c in unicodedata.normalize('NFD', texto)
        if unicodedata.category(c) != 'Mn'
    )

    mapa = {
        "PODEMOS": "PODE",
        "REPUBLICAN": "REPUBLICANOS",
        "SOLIDARIED": "SOLIDARIEDADE",
        "NOVO": "NOVO",
        "AVANTE": "AVANTE",
        "PATRIOTA": "PATRIOTA",
        "UNIAO": "UNIAO"
    }

    return mapa.get(texto, texto)

votacoesOrientacoes["siglabancada_join"] = (
    votacoesOrientacoes["siglabancada"]
    .apply(normalizar_partido)
)

print(
    votacoesOrientacoes["siglabancada_join"]
    .value_counts()
)

votacoesVotos = dataframes["votacoesVotos"].copy()

votacoesVotos["partido_join"] = (
    votacoesVotos["deputado_siglapartido"]
    .apply(normalizar_partido)
)

votacoesVotos = votacoesVotos.drop(
    columns=[
        "siglabancada",
        "orientacao",
        "alinhado"
    ],
    errors="ignore"
)

votacoesVotos = votacoesVotos.merge(
    votacoesOrientacoes[
        [
            "idvotacao",
            "siglabancada_join",
            "orientacao"
        ]
    ],
    left_on=[
        "idvotacao",
        "partido_join"
    ],
    right_on=[
        "idvotacao",
        "siglabancada_join"
    ],
    how="left"
)

def calcular_alinhamento(voto, orientacao):

    if pd.isna(orientacao):
        return None

    voto = str(voto).strip().upper()
    orientacao = str(orientacao).strip().upper()

    if voto == orientacao:
        return 1

    return 0


votacoesVotos["alinhado"] = votacoesVotos.apply(
    lambda row: calcular_alinhamento(
        row["voto"],
        row["orientacao"]
    ),
    axis=1
)

dataframes["votacoesVotos"] = votacoesVotos.copy()

print(
    dataframes["votacoesVotos"]["alinhado"]
    .value_counts(dropna=False)
)

print(
    votacoesVotos.groupby(
        "deputado_siglapartido"
    )["orientacao"]
    .apply(lambda x: x.notna().mean()*100)
    .sort_values()
)

print("\n=== ETAPA 4: SALVANDO CSVs TRATADOS ===")

for nome, df in dataframes.items():
    destino = os.path.join(PROC_PATH, f"{nome}_tratado.csv")
    df.to_csv(destino, index=False, encoding="utf-8")
    print(f"  [OK] {destino}")

print("\n=== ETAPA 5: CARGA NO SQLite ===")

TABELAS_SQL = {
    "deputados": "Deputados",
    **{nome: cfg["tabela_sql"] for nome, cfg in FONTES.items()},
}

with sqlite3.connect(DB_PATH) as conn:

    conn.execute("PRAGMA encoding = 'UTF-8'")

    for nome, df in dataframes.items():
        tabela = TABELAS_SQL.get(nome, nome)
        df.to_sql(tabela, conn, if_exists="replace", index=False)
        print(f"  [OK] '{tabela}': {len(df):,} linhas")

    teste = pd.read_sql("SELECT * FROM Deputados LIMIT 3", conn)
    print("\n[TESTE] Amostra de Deputados:")
    display(teste)

    # Teste de encoding nas despesas
    teste_enc = pd.read_sql(
        "SELECT txtdescricao FROM Despesas WHERE txtdescricao IS NOT NULL LIMIT 5",
        conn
    )
    print("\n[TESTE] Encoding txtDescricao:")
    display(teste_enc)

print(f"\n[FINALIZADO] Pipeline {ANO_INICIO}–{ANO_FIM} concluído com sucesso.")